/**
 * This file is autogenerated by Scaffold-ETH noir-starter-kit.
 * You should not edit it manually or your changes might be overwritten.
 */

const nargoCircuits: Record<string, any> = {} as const;

export default nargoCircuits;
