import fs from 'fs';
import prettier from "prettier";

const targetDir   = `${__dirname}/../target`;

const generatedContractComment = `
/**
 * This file is autogenerated by Scaffold-ETH noir-starter-kit.
 * You should not edit it manually or your changes might be overwritten.
 */
`;

export async function publishNargoCircuits(circuitsList: string[]) {
    circuitsList = circuitsList.map(
      (name: string) => { return name.replace("circuits/", "") }
    );
  
    const nextCircuitsDir = `${__dirname}/../../nextjs/circuits`;
  
    const circuitsInfo: Record<string, any> = {};
  
    for (let i = 0; i<circuitsList.length; i++) {
      const circuitJSON = JSON.parse(
        fs.readFileSync(`${targetDir}/${circuitsList[i]}.json`).toString()
      );
      // @TODO remove local file structure info from being included in the publish
    //   console.log(circuitJSON)
      delete circuitJSON.file_map
    //   console.log(circuitJSON)
    
      circuitsInfo[circuitsList[i]] = circuitJSON;
    }
  
    // if (Object.keys(circuitsInfo).length > 0) {
    
      if (!fs.existsSync(nextCircuitsDir)) {
        fs.mkdirSync(nextCircuitsDir);
      }
      try {
        fs.writeFileSync(
          `${nextCircuitsDir}/nargoCircuits.ts`,
          // @ts-ignore
          await prettier.format(
            `${generatedContractComment} \n\n
            const nargoCircuits: Record<string, any> = ${JSON.stringify(circuitsInfo)} as const; \n\n export default nargoCircuits`,
            {
              parser: "typescript",
            },
          ),
        );
      } catch (e) {
        console.error(e);
        process.exit();
      }
    // } else {
  
    // }
  }